package com.duggustore.app.data.repository

import com.duggustore.app.data.model.Category
import com.duggustore.app.data.remote.SessionManager
import com.duggustore.app.data.remote.SupabaseService
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

private val json = Json { ignoreUnknownKeys = true; coerceInputValues = true }

class CategoryRepository {

    private fun token(): String? = SessionManager.getAccessToken()

    /** Writable columns only — `id` is generated by the database. */
    private fun body(category: Category): JsonObject = buildJsonObject {
        put("name", category.name)
        category.iconUrl?.let { put("icon_url", it) }
        put("color_hex", category.colorHex)
        put("sort_order", category.sortOrder)
        put("is_active", category.isActive)
    }

    /**
     * Only the categories a seller has actually put something in — what the
     * storefront offers to browse.
     *
     * The catalogue is seeded far wider than current stock so sellers have
     * somewhere precise to file things, and an empty category is a dead end
     * to a shopper, not a choice. The filtering is a SECURITY DEFINER
     * function rather than a client-side pass so the empty ones never leave
     * the database in the first place.
     *
     * Admin keeps using [getAllCategories] — organising the empty ones is
     * exactly its job.
     */
    suspend fun getStockedCategories(): Result<List<Category>> {
        return try {
            val body = SupabaseService.rpc("stocked_categories", token = token())
            Result.success(
                json.decodeFromString(ListSerializer(Category.serializer()), body)
            )
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun getAllCategories(): Result<List<Category>> {
        return try {
            val list = SupabaseService.selectAll("categories", token())
            Result.success(
                list.map { json.decodeFromString(Category.serializer(), it.toString()) }
                    .sortedBy { it.sortOrder }
            )
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    /**
     * One category by id — the product page needs its name for the
     * specification table's first row. Asking for the single row rather than
     * pulling the whole catalogue keeps opening a product from a deep link or
     * a notification from fetching every category in the store.
     */
    suspend fun getCategoryById(id: String): Result<Category?> {
        return try {
            val rows = SupabaseService.select("categories", token(), mapOf("id" to id))
            Result.success(
                rows.firstOrNull()?.let { json.decodeFromString(Category.serializer(), it.toString()) }
            )
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun createCategory(category: Category): Result<Unit> {
        return try {
            SupabaseService.insert("categories", body(category).toString(), token())
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun updateCategory(category: Category): Result<Unit> {
        return try {
            SupabaseService.update("categories", category.id, body(category).toString(), token())
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }

    suspend fun deleteCategory(id: String): Result<Unit> {
        return try {
            SupabaseService.delete("categories", id, token())
            Result.success(Unit)
        } catch (e: Exception) {
            Result.failure(e)
        }
    }
}
